### PR TITLE
Example Machines selectable in live editor

### PR DESCRIPTION
**Pull request by machinshin**

### CODE REVIEW

**Comment by machinshin** [comment]
still has 2 issues, 
1/ when you click/show a machine, the editor view is selected
2/ store previous selected machine in localStorage?

**Comment by StoneCypher** [comment]
oh wow how did you mark this a work in progress?  i've never seen that before and i'm gonna use the shit out of that

**Comment by StoneCypher** [comment]
1. If you want, you can call `.focus()` on the editor and it'll re-focus
2. You could if you wanted to but I think that's probably overkill

Some things I'd like:

1. I'd like the first item in the dropdown to be "examples" and disabled so that people know what the dropdown is
2. I'd like the dropdown to be narrower by half please
3. The example code is weirdly indented because the strings are indented

Those three things fixed, and your call on point 1, and I'm happy to merge this

**Comment by machinshin** [comment]
> 1. If you want, you can call `.focus()` on the editor and it'll re-focus

 cool. thanks

>     2. You could if you wanted to but I think that's probably overkill
  I like the idea, so I'm gonna implement it :)

>     1. I'd like the first item in the dropdown to be "examples" and disabled so that people 
> know what the dropdown is

Noted

>     2. I'd like the dropdown to be narrower by half please
Will do

>     3. The example code is weirdly indented because the strings are indented
Yes, I copy-pasted from the raw file content

> oh wow how did you mark this a work in progress? i've never seen that before and i'm gonna use the shit out of that

When you create a PR there are 2 buttons, one for "Create PR" & another for "Create Draft PR"

**Comment by StoneCypher** [comment]
> > 3. The example code is weirdly indented because the strings are indented
>
> Yes, I copy-pasted from the raw file content

That's not what I mean

Your variables look like this:

```typescript
    var foo = `
      a -> b;
    `;
```

That means that they come up in the editor indented too

image

**Comment by machinshin** [comment]
@StoneCypher let me know if you want any more changes

**Pull request merged**
