### PR TITLE
update jssm-viz version

### PR DESCRIPTION
**Pull request by machinshin**

### CODE REVIEW

**Comment by StoneCypher** [comment]
is this up to date?  i thought i remembered there being a version block somewhere but i don't remember where

**Comment by machinshin** [comment]
Yah it's up to date with the current jssm-viz version, but as mentioned in chat I get other errors/warnings (like highlight.js v9 being EOL) when trying to build that current jssm-viz version

**Comment by StoneCypher** [comment]
Gross, there's no action here.  

This is my fault - we should be able to look at the error log together.  Will fix with a github action

For now could you cut and paste the errors here so we can review them together?

**Comment by StoneCypher** [comment]
Nevermind the copy pasta.  I've made a GH action.

Please merge against `master`.  That'll let me see what you're seeing.  (Lion-O, use the sword.)

After you land this, I'll change `master`'s name to `main`.

**Comment by StoneCypher** [comment]
oh, the iife build is just missing, i probably screwed up the build.  will fix, sec

the way you check this is to just look at that path it's saying

```
cp: cannot stat './node_modules/jssm-viz/dist/jssm-viz.iife.js': No such file or directory
```

okay?

```
$ ls node_modules/jssm-viz/dist/
jssm-viz.cjs.js  jssm-viz.es6.js
```

oh.  there's a commonjs one and an es6 one, but no iife one.

derp

**Comment by machinshin** [comment]
@StoneCypher : i think that means you should merge this PR? : https://github.com/StoneCypher/jssm-viz/pull/27

**Comment by StoneCypher** [comment]
Probably.  Lemme set up an action first just in case

**Comment by StoneCypher** [comment]
Oh you already knew what was wrong

**Comment by machinshin** [comment]
```
 vat@izi-hq  ~/workspace/fsl/jssm-viz-demo   master  npm run build                                                                                                   ✔  1864  14:35:00
Alias tip: nr build

> jssm-viz-demo@1.11.0 build /Users/vat/workspace/fsl/jssm-viz-demo
> npm run clean && npm run clone


> jssm-viz-demo@1.11.0 clean /Users/vat/workspace/fsl/jssm-viz-demo
> rm -rf ./docs/ && mkdir docs


> jssm-viz-demo@1.11.0 clone /Users/vat/workspace/fsl/jssm-viz-demo
> npm run clonejs && npm run clonehtml && npm run cloneace


> jssm-viz-demo@1.11.0 clonejs /Users/vat/workspace/fsl/jssm-viz-demo
> cp ./node_modules/jssm-viz/dist/jssm-viz.iife.js ./docs/

cp: ./node_modules/jssm-viz/dist/jssm-viz.iife.js: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jssm-viz-demo@1.11.0 clonejs: `cp ./node_modules/jssm-viz/dist/jssm-viz.iife.js ./docs/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jssm-viz-demo@1.11.0 clonejs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vat/.npm/_logs/2021-04-27T21_35_03_614Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jssm-viz-demo@1.11.0 clone: `npm run clonejs && npm run clonehtml && npm run cloneace`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jssm-viz-demo@1.11.0 clone script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vat/.npm/_logs/2021-04-27T21_35_03_637Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jssm-viz-demo@1.11.0 build: `npm run clean && npm run clone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jssm-viz-demo@1.11.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vat/.npm/_logs/2021-04-27T21_35_03_670Z-debug.log
```

**Comment by StoneCypher** [comment]
so i think this needs a version bump and a re-build because most of the build products are removed

**Comment by machinshin** [comment]
ok, so the current version is 1.11.0, should i make a bump to the minor (1.11.1) or mid (1.12.0) ?

**Comment by StoneCypher** [comment]
it's just a library dep.  probably just a patch

**Review by StoneCypher — APPROVED** [review]

**Pull request merged**
